name: Bug Report
description: Report a bug in qr-sampler
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill in the details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Set QR_ENTROPY_SOURCE_TYPE=...
        2. Run vllm serve ...
        3. Send request ...
        4. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened (include error messages and stack traces).
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: "3.12.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "Ubuntu 24.04 / macOS 15 / Windows 11"
    validations:
      required: true

  - type: input
    id: vllm-version
    attributes:
      label: vLLM version (if applicable)
      placeholder: "0.6.0"

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant QR_* environment variables.
      render: bash
