name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature. Please describe what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve? Why is it needed?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you've considered.

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Entropy source
        - Signal amplification
        - Temperature strategy
        - Token selection
        - Configuration
        - Logging / diagnostics
        - gRPC protocol
        - Documentation
        - Other
    validations:
      required: true
